### ISSUE TITLE
File explorer settings crash

### ISSUE THREAD

**Issue by GigilinE** [BIOLorenz/Xiaomi.eu-MIUI_v14-Italian#22]
File explorer go in crash when click settings, i can't also choose file lut in camera for problem, i think is releated with this problem, i have last stable hyperos xiaomi 14 ultra

**Comment by Hackintosh98** [comment]
**first of all,** this is a Italian translator repository for MIUI14, not HyperOS.
For HyperOS translation see https://github.com/Hackintosh98/HyperOS-XML-1.0-Italian

**Second**
I think this problem is not related to translation problem but Rom Issue. If you think problem is related to language problem, then please send me logs.
Thanks
